### ISSUE TITLE
Need change in description in START RIDES homepage

### ISSUE THREAD

**Issue by domino416** [easi6/startup-rides#2]
![image](https://cloud.githubusercontent.com/assets/16145545/15240435/8fd5f9da-1924-11e6-9020-759abb06f8f6.png)

Please change the highlighted part into: 

Enjoy a chance to meet the right investor for your company on a city ride in Hong Kong!
Hosted by Easiway, IBM Softlayer and supported by Rise Conference, we have prepared Tesla rides as a meeting place with investors to make the event friendlier. 
If you want to join us, please submit your application right now!

**Comment by drunkhacker** [comment]
I’ll take that. Thanks

**Comment by drunkhacker** [comment]
Woh. it is already applied at source code. I’ll update main page.

**Comment by drunkhacker** [comment]
it's done now.

**Comment by domino416** [comment]
감사합니다
